"""Pydantic models for the backend HTTP API."""

from __future__ import annotations

from typing import Dict, List, Literal, Sequence

from pydantic import BaseModel, Field


class ChatTurn(BaseModel):
    """Single turn exchanged between the player and an NPC."""

    role: Literal["user", "assistant"]
    content: str = Field(..., min_length=1)


class ChatRequest(BaseModel):
    """Payload that kicks off an LLM completion."""

    npc_id: str = Field(..., description="Identifier of the NPC to converse with.")
    message: str = Field(..., description="Player's latest utterance.", min_length=1)
    history: Sequence[ChatTurn] = Field(
        default_factory=list,
        description="Prior conversation turns in chronological order.",
    )
    language: str = Field(
        default="en",
        description="Language code for NPC responses ('en' or 'sr').",
    )
    pressure: int = Field(
        default=0,
        ge=0,
        le=100,
        description="Current hidden pressure value for this NPC (0–100).",
    )
    rapport: int = Field(
        default=25,
        ge=0,
        le=100,
        description="Current hidden rapport value for this NPC (0–100). Starts at 25 (neutral).",
    )
    player_evidence_ids: List[str] = Field(
        default_factory=list,
        description="Evidence IDs the player has collected so far.",
    )
    player_discovery_ids: List[str] = Field(
        default_factory=list,
        description="Discovery IDs the player has already collected.",
    )
    peak_pressure: int = Field(
        default=0,
        ge=0,
        le=100,
        description="Highest pressure this NPC has ever reached (0–100).",
    )
    session_id: str | None = Field(
        default=None,
        description="Client-generated session UUID for gameplay tracking.",
    )


class ChatResponse(BaseModel):
    """Response payload returned to the front-end."""

    reply: str = Field(..., description="NPC response generated by the LLM.")
    npc_id: str
    history: List[ChatTurn]
    evidence_ids: List[str] = Field(
        default_factory=list,
        description="Evidence category IDs derived from discoveries revealed in this reply.",
    )
    discovery_ids: List[str] = Field(
        default_factory=list,
        description="Specific discovery IDs the NPC revealed in this reply.",
    )
    discovery_summaries: Dict[str, str] = Field(
        default_factory=dict,
        description="Map from discovery_id to a faithful 1-sentence summary of what the NPC revealed.",
    )
    expression: str = Field(
        default="neutral",
        description="NPC emotional expression for this reply.",
    )
    pressure: int = Field(
        default=0,
        description="Updated hidden pressure value after this turn.",
    )
    rapport: int = Field(
        default=25,
        description="Updated hidden rapport value after this turn.",
    )
    pressure_band: str = Field(
        default="calm",
        description="Qualitative pressure band (calm/tense/shaken/cornered).",
    )
    rapport_band: str = Field(
        default="neutral",
        description="Qualitative rapport band (cold/neutral/open/trusting).",
    )
    tactic_type: str = Field(
        default="open_ended",
        description="Classified interrogation tactic for this turn.",
    )
    evidence_strength: str = Field(
        default="none",
        description="Classified evidence strength for this turn.",
    )
    peak_pressure: int = Field(
        default=0,
        description="Updated peak pressure after this turn (max of old peak and new pressure).",
    )


class SpeakRequest(BaseModel):
    """Payload for the text-to-speech endpoint."""

    text: str = Field(..., description="Text to convert to speech.", min_length=1, max_length=4096)
    voice: str = Field(default="alloy", description="OpenAI TTS voice identifier.")


__all__ = ["ChatTurn", "ChatRequest", "ChatResponse", "SpeakRequest"]
