"""Pydantic models for the backend HTTP API."""

from __future__ import annotations

from typing import List, Literal, Sequence

from pydantic import BaseModel, Field


class ChatTurn(BaseModel):
    """Single turn exchanged between the player and an NPC."""

    role: Literal["user", "assistant"]
    content: str = Field(..., min_length=1)


class ChatRequest(BaseModel):
    """Payload that kicks off an LLM completion."""

    npc_id: str = Field(..., description="Identifier of the NPC to converse with.")
    message: str = Field(..., description="Player's latest utterance.", min_length=1)
    history: Sequence[ChatTurn] = Field(
        default_factory=list,
        description="Prior conversation turns in chronological order.",
    )
    language: str = Field(
        default="en",
        description="Language code for NPC responses ('en' or 'sr').",
    )


class ChatResponse(BaseModel):
    """Response payload returned to the front-end."""

    reply: str = Field(..., description="NPC response generated by the LLM.")
    npc_id: str
    history: List[ChatTurn]
    evidence_ids: List[str] = Field(
        default_factory=list,
        description="Evidence IDs the NPC revealed in this reply.",
    )
    expression: str = Field(
        default="neutral",
        description="NPC emotional expression for this reply.",
    )


class SpeakRequest(BaseModel):
    """Payload for the text-to-speech endpoint."""

    text: str = Field(..., description="Text to convert to speech.", min_length=1, max_length=4096)
    voice: str = Field(default="alloy", description="OpenAI TTS voice identifier.")


__all__ = ["ChatTurn", "ChatRequest", "ChatResponse", "SpeakRequest"]
